import socket

DATASET_DIR = None
METADATA_DIR = None
REPLAY_FROM_METASTORE = None
SERVER_PORT = None
CLIENTS_FOLDER = None
EPOCH_STATUS_FILE = None
MODELS_FOLDER = None
CLIENTS = {}
CURRENT_MAX_ITERATION = None
MODELS_IN_TRAINING = {}
MODELS_GENERATED = {}
CURRENT_MAX_CLIENT_ID = None

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('8.8.8.8', 1))

IP_ADDRESS = s.getsockname()[0]
